name: Danger

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Bundle install
      run: gem install bundler && bundle install
    - name: Apply lint
      run: ./gradlew spotlessKotlinApply
    - name: Run danger
      uses: reviewdog/action-suggester@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tool_name: spotless
